language: "jp"
early_access: false
reviews:
  high_level_summary: false
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    -  "**/*.py"
  path_instructions:
    - path: "**/*.py"
      instructions: "Review the Python code for conformity with the PEP8 style guide, highlighting any deviations."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "develop"
      - "feat/*"
      - "submit/*"
chat:
  auto_reply: false
